### ISSUE TITLE
Infografía de RA.

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Rigoberto2001#1]
[Infografía Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Rigoberto2001/files/10746493/Infografia.Realidad.Aumentada.pdf)

**Comment by CxrlosMX** [comment]
Excelente trabajo: 20/20 calificación

**Comment by josealfredo79** [comment]
Bien hecho y revisado
